services:
  db:
    image: postgres:16-alpine
    container_name: conference_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: conference_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d conference_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    build: .
    container_name: conference_api
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_DB: conference_db
      DATABASE_URL: postgresql+asyncpg://postgres:postgres@db:5432/conference_db
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:
