from datetime import date
from decimal import Decimal

from pydantic import BaseModel, ConfigDict, Field


class RoomOccupancy(BaseModel):
    room_id: int = Field(..., description="Room identifier", examples=[1])
    room_name: str = Field(..., description="Room name", examples=["Room A"])
    total_booked_hours: Decimal = Field(
        ...,
        description="Total hours reserved within operating windows (06:00 - 23:00)",
        examples=[Decimal("17.00")],
    )
    available_hours: Decimal = Field(
        ...,
        description="Total available operating hours across the period (days * 17h)",
        examples=[Decimal("34.00")],
    )
    occupancy_rate_pct: Decimal = Field(
        ...,
        description="Room occupancy rate percentage",
        examples=[Decimal("50.00")],
    )

    model_config = ConfigDict(from_attributes=True)


class OccupancyReportResponse(BaseModel):
    start_date: date = Field(
        ..., description="Report start date", examples=["2026-11-01"]
    )
    end_date: date = Field(..., description="Report end date", examples=["2026-11-02"])
    days_count: int = Field(
        ..., description="Total days in report period", examples=[2]
    )
    rooms: list[RoomOccupancy] = Field(
        default_factory=list,
        description="Occupancy statistics broken down per active room",
    )


class RevenueReportResponse(BaseModel):
    start_date: date = Field(
        ..., description="Report start date", examples=["2026-11-01"]
    )
    end_date: date = Field(..., description="Report end date", examples=["2026-11-02"])
    total_revenue: Decimal = Field(
        ...,
        description="Total combined revenue from rentals and services",
        examples=[Decimal("12500.00")],
    )
    rooms_revenue: Decimal = Field(
        ...,
        description="Revenue derived purely from room hour rental fees",
        examples=[Decimal("10000.00")],
    )
    services_revenue: Decimal = Field(
        ...,
        description="Revenue derived from additional ordered services",
        examples=[Decimal("2500.00")],
    )


class PopularServiceItem(BaseModel):
    service_id: int = Field(..., description="Service ID", examples=[1])
    service_name: str = Field(..., description="Service name", examples=["Projector"])
    order_count: int = Field(
        ..., ge=0, description="Total number of times ordered", examples=[15]
    )
    total_revenue: Decimal = Field(
        ...,
        description="Cumulative revenue generated by this service",
        examples=[Decimal("7500.00")],
    )

    model_config = ConfigDict(from_attributes=True)


class PopularServicesResponse(BaseModel):
    services: list[PopularServiceItem] = Field(
        default_factory=list,
        description="Ranking of services by demand and generated revenue",
    )
